import { type ReactNode, useEffect, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Check, Clock3, Dumbbell, Instagram, MapPin, Menu, MessageCircle, MoveRight, Phone, ShieldCheck, Star, X } from 'lucide-react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Route, Switch, useLocation, Router as WouterRouter } from 'wouter';
import { gymContent } from '@/content';
import '@/index.css';

const queryClient = new QueryClient();
const reveal = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: .7, ease: [0.22, 1, 0.36, 1] as const } } };
const stagger = { hidden: {}, show: { transition: { staggerChildren: .11 } } };

function useScrolled() {
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 36);
    window.addEventListener('scroll', onScroll, { passive: true }); onScroll();
    return () => window.removeEventListener('scroll', onScroll);
  }, []);
  return scrolled;
}
function Anchor({ href, children, className = '' }: { href: string; children: ReactNode; className?: string }) {
  return <a href={href} className={className} data-testid={`link-${href.replace('#', '')}`}>{children}</a>;
}
function Header() {
  const compact = useScrolled(); const [open, setOpen] = useState(false);
  const links = [['#programs', 'Programs'], ['#coaches', 'Coaches'], ['#inside', 'Inside Titan'], ['#visit', 'Visit us']];
  return <header className={`fixed top-0 z-40 w-full transition-all duration-500 ${compact ? 'border-b border-white/10 bg-[#10131b]/95 backdrop-blur-md' : 'bg-transparent'}`}>
    <div className={`mx-auto flex max-w-[1440px] items-center justify-between px-5 transition-all md:px-10 ${compact ? 'h-[68px]' : 'h-[88px]'}`}>
      <Anchor href="#" className="group flex items-center gap-3"><span className="grid size-9 place-items-center border border-[#d6ff4b]/50 bg-[#d6ff4b] text-[#10131b]"><Dumbbell size={19} strokeWidth={2.5} /></span><span className="font-display text-[24px] font-extrabold uppercase leading-none tracking-tight text-[#f3f2ea]">Titan<span className="text-[#d6ff4b]">.</span></span></Anchor>
      <nav className="hidden items-center gap-8 lg:flex">{links.map(([href, label]) => <Anchor key={href} href={href} className="eyebrow text-[#d9dce5]/70 transition-colors hover:text-[#d6ff4b]">{label}</Anchor>)}</nav>
      <div className="hidden items-center gap-4 sm:flex"><a href={`tel:${gymContent.business.phone.replaceAll(' ', '')}`} className="eyebrow flex items-center gap-2 text-[#d9dce5]/70 hover:text-[#d6ff4b]" data-testid="link-phone-header"><Phone size={14} /><span className="hidden xl:inline">{gymContent.business.phone}</span></a><a href={gymContent.business.whatsapp} target="_blank" rel="noreferrer" className="group flex items-center gap-2 bg-[#d6ff4b] px-4 py-3 text-[11px] font-bold uppercase tracking-[.14em] text-[#10131b] transition-transform hover:-translate-y-0.5" data-testid="link-whatsapp-header">Message us <ArrowUpRight size={15} /></a></div>
      <button onClick={() => setOpen(!open)} className="grid size-10 place-items-center border border-white/15 text-[#f3f2ea] sm:hidden" aria-label="Toggle menu" data-testid="button-menu-toggle">{open ? <X size={21} /> : <Menu size={21} />}</button>
    </div>
    {open && <div className="border-t border-white/10 bg-[#10131b] px-5 pb-6 pt-4 sm:hidden">{links.map(([href, label]) => <Anchor key={href} href={href} className="eyebrow block border-b border-white/10 py-4 text-[#f3f2ea]">{label}</Anchor>)}<a href={gymContent.business.whatsapp} target="_blank" rel="noreferrer" className="mt-4 flex items-center justify-center gap-2 bg-[#d6ff4b] py-4 text-xs font-bold uppercase tracking-widest text-[#10131b]" data-testid="link-whatsapp-mobile">Message Titan <MessageCircle size={16} /></a></div>}
  </header>;
}
function Hero() {
  const reduce = useReducedMotion();
  return <section className="relative flex min-h-[780px] items-end overflow-hidden bg-[#10131b] pt-28 md:min-h-[860px]"><div className="hero-grid absolute inset-0 opacity-60" /><motion.div initial={reduce ? false : { scale: 1.06, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: 1.5 }} className="hero-image absolute inset-0 bg-cover bg-center md:bg-[position:58%_center]" style={{ backgroundImage: "linear-gradient(90deg, #10131b 0%, rgba(16,19,27,.82) 33%, rgba(16,19,27,.18) 72%, #10131b 100%), linear-gradient(0deg, #10131b 0%, transparent 45%), url('/titan-hero.jpg')" }} /><div className="absolute right-[8%] top-[19%] hidden h-24 w-24 border-r border-t border-[#d6ff4b]/50 md:block" />
    <div className="relative z-10 mx-auto w-full max-w-[1440px] px-5 pb-20 md:px-10 md:pb-28"><motion.div initial="hidden" animate="show" variants={stagger} className="max-w-[850px]"><motion.div variants={reveal} className="mb-7 flex items-center gap-3"><span className="h-px w-12 bg-[#d6ff4b]" /><span className="eyebrow text-[#d6ff4b]">Clifton, Karachi · Est. for the committed</span></motion.div><motion.h1 variants={reveal} className="font-display display-shadow max-w-[850px] text-[clamp(4.5rem,12vw,11.5rem)] font-black uppercase leading-[.78] tracking-[-.045em] text-[#f3f2ea]">Train<br /><span className="text-[#d6ff4b]">like it</span><br />matters<span className="text-[#ff725f]">.</span></motion.h1><motion.p variants={reveal} className="mt-9 max-w-[430px] text-base leading-7 text-[#d9dce5]/75 md:text-lg">A serious training space for people who are done negotiating with their potential. Expert trainers. Endurance training. Real work.</motion.p><motion.div variants={reveal} className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={gymContent.business.whatsapp} target="_blank" rel="noreferrer" className="group inline-flex items-center justify-center gap-3 bg-[#d6ff4b] px-6 py-4 text-xs font-bold uppercase tracking-[.15em] text-[#10131b] transition-transform hover:-translate-y-1" data-testid="link-whatsapp-hero">Ask about membership <MoveRight size={17} /></a><Anchor href="#programs" className="inline-flex items-center justify-center gap-3 border border-white/25 px-6 py-4 text-xs font-bold uppercase tracking-[.15em] text-[#f3f2ea] hover:border-[#d6ff4b] hover:text-[#d6ff4b]">Explore the floor <ArrowDownRight size={17} /></Anchor></motion.div></motion.div><div className="mt-20 grid max-w-3xl grid-cols-2 gap-y-6 border-t border-white/15 pt-6 sm:grid-cols-4 md:mt-28" data-testid="stats-hero">{[['4.7★', '107 Google reviews'], ['1.8K+', 'Facebook followers'], ['1.4K+', 'Instagram followers'], ['16 hrs', 'Weekday access']].map(([value, label]) => <div key={label} className="border-r border-white/10 last:border-0"><div className="font-display text-3xl font-bold text-[#f3f2ea]">{value}</div><div className="eyebrow mt-1 text-[#d9dce5]/50">{label}</div></div>)}</div></div><div className="absolute bottom-7 right-6 hidden items-center gap-3 md:flex"><span className="eyebrow text-[#d9dce5]/45">Scroll to train</span><span className="grid size-9 place-items-center rounded-full border border-white/20 text-[#d6ff4b]"><ArrowDownRight size={16} /></span></div>
  </section>;
}
function Marquee() {
  return <div className="overflow-hidden border-y border-[#26303e] bg-[#171c27] py-4 text-[#d6ff4b]"><div className="marquee flex w-max items-center gap-8 whitespace-nowrap">{Array.from({ length: 2 }).flatMap((_, i) => ['NO SHORTCUTS', 'CLIFTON / KARACHI', 'SHOW UP', 'GET STRONGER', 'TITAN FITNESS GYM'].map((text, j) => <span key={`${i}-${j}`} className="flex items-center gap-8 font-display text-xl font-bold uppercase tracking-[.13em]">{text}<span className="text-[#ff725f]">/</span></span>))}</div></div>;
}
function SectionHeading({ kicker, title, body, light = false }: { kicker: string; title: ReactNode; body?: string; light?: boolean }) {
  return <div className="mb-14 max-w-3xl"><div className={`eyebrow mb-5 flex items-center gap-3 ${light ? 'text-[#d6ff4b]' : 'text-[#ff725f]'}`}><span className="h-px w-8 bg-current" />{kicker}</div><h2 className={`font-display text-[clamp(3.5rem,7vw,7rem)] font-black uppercase leading-[.82] tracking-[-.035em] ${light ? 'text-[#f3f2ea]' : 'text-[#10131b]'}`}>{title}</h2>{body && <p className={`mt-7 max-w-xl text-base leading-7 ${light ? 'text-[#d9dce5]/65' : 'text-[#4b5360]'}`}>{body}</p>}</div>;
}
function Programs() {
  return <section id="programs" className="bg-[#ecebe4] px-5 py-24 md:px-10 md:py-36"><div className="mx-auto max-w-[1440px]"><motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: .15 }} variants={reveal}><SectionHeading kicker="How we train" title={<>Your goal.<br /><span className="text-[#ff725f]">Our floor.</span></>} body="There is no one-size-fits-all version of strong. Pick the work that fits where you are going, then let our coaches help you get there." /></motion.div><div className="grid gap-px bg-[#bfc0b7] md:grid-cols-2">{gymContent.programs.map(program => <motion.article key={program.number} initial="hidden" whileInView="show" viewport={{ once: true, amount: .2 }} variants={reveal} className="group relative min-h-[310px] overflow-hidden bg-[#ecebe4] p-7 transition-colors duration-500 hover:bg-[#f4f3ed] md:p-10"><div className={`absolute left-0 top-0 h-1 w-24 ${program.accent === 'lime' ? 'bg-[#b8dd32]' : 'bg-[#ff725f]'}`} /><div className="flex items-start justify-between"><span className="font-mono-brand text-xs text-[#6e746f]">{program.number} / 04</span><span className="eyebrow text-[#6e746f]">{program.label}</span></div><h3 className="mt-16 max-w-xs font-display text-5xl font-bold uppercase leading-[.84] tracking-tight text-[#10131b] md:text-6xl">{program.title}</h3><p className="mt-5 max-w-sm text-sm leading-6 text-[#59605f]">{program.copy}</p><div className="mt-6 flex flex-wrap gap-2">{program.points.map(point => <span key={point} className="inline-flex items-center gap-1.5 border border-[#c8c9c1] px-2.5 py-1.5 text-[10px] font-semibold uppercase tracking-widest text-[#59605f]"><Check size={11} />{point}</span>)}</div><ArrowUpRight className="absolute bottom-8 right-8 text-[#a6aaa1] transition-all duration-300 group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[#ff725f]" size={25} /></motion.article>)}</div></div></section>;
}
function Credibility() {
  const standards = [['01', 'Clean by design', 'A training environment you can focus in, with equipment and spaces kept ready for the next round.'], ['02', 'Coaches who know', 'Guidance for weight loss, muscle gain, endurance, and bodybuilding — without the ego.'], ['03', 'For every body', 'Personal and group / ground training available for both men and women.'], ['04', 'Open late', 'Weekday access from 8:00 AM through midnight, so consistency can fit real life.']];
  return <section className="bg-[#10131b] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-[1440px] items-start gap-16 lg:grid-cols-[1fr_1.4fr]"><motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={reveal}><SectionHeading light kicker="The Titan standard" title={<>No theatre.<br /><span className="text-[#d6ff4b]">Just work.</span></>} body="From the first rep to the last round, Titan is built to make progress feel possible. A clean environment, friendly knowledgeable staff, and the kind of atmosphere that pulls you back in." /></motion.div><div className="grid gap-0 sm:grid-cols-2">{standards.map(([no, title, copy]) => <motion.div initial="hidden" whileInView="show" viewport={{ once: true }} variants={reveal} key={no} className="border-t border-white/15 py-7 sm:px-7 sm:first:pl-0"><span className="font-mono-brand text-xs text-[#ff725f]">{no}</span><h3 className="mt-8 font-display text-3xl font-bold uppercase tracking-tight text-[#f3f2ea]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#d9dce5]/55">{copy}</p></motion.div>)}</div></div></section>;
}
function Pricing() {
  const [selected, setSelected] = useState('Open gym');
  return <section className="bg-[#d6ff4b] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1440px]"><div className="grid gap-14 lg:grid-cols-[.85fr_1.5fr] lg:gap-24"><div><div className="eyebrow mb-5 flex items-center gap-3 text-[#10131b]/65"><span className="h-px w-8 bg-[#10131b]" />Make the move</div><h2 className="font-display text-[clamp(4rem,8vw,8.5rem)] font-black uppercase leading-[.78] tracking-[-.04em] text-[#10131b]">Start<br />where<br /><span className="text-[#ff725f]">you are.</span></h2><p className="mt-8 max-w-sm text-sm leading-6 text-[#26301f]">Pricing changes. Your first message is simple. Tell us what you want to work on and we will confirm the right membership or training option.</p><a href={gymContent.business.whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-3 border-b-2 border-[#10131b] pb-2 text-xs font-bold uppercase tracking-widest text-[#10131b]" data-testid="link-whatsapp-pricing">Ask for current rates <ArrowUpRight size={16} /></a></div><div className="lg:pt-6">{gymContent.pricing.map(item => <button type="button" key={item.title} onClick={() => setSelected(item.title)} className={`group flex w-full items-end justify-between border-t border-[#10131b]/20 py-7 text-left transition-all ${selected === item.title ? 'pl-4' : ''}`} data-testid={`button-pricing-${item.title.toLowerCase().replaceAll(' ', '-')}`}><div><div className="font-display text-4xl font-bold uppercase leading-none text-[#10131b] md:text-5xl">{item.title}</div><div className="mt-2 text-sm text-[#26301f]/70">{item.detail}</div></div><div className="text-right"><div className="font-mono-brand text-xl font-bold text-[#10131b]">{item.price}</div><div className="eyebrow mt-2 text-[#26301f]/60">{item.note}</div></div></button>)}<div className="mt-5 flex items-center gap-2 text-xs font-semibold text-[#10131b]/65"><ShieldCheck size={16} /> Owner confirmation placeholders are intentionally marked.</div></div></div></div></section>;
}
function Coaches() {
  return <section id="coaches" className="bg-[#ecebe4] px-5 py-24 md:px-10 md:py-36"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionHeading kicker="The people behind the push" title={<>Good coaching<br /><span className="text-[#ff725f]">changes everything.</span></>} /><span className="eyebrow mb-14 max-w-[190px] text-[#59605f]">Trainer names and profiles shown as confirmation placeholders</span></div><div className="grid gap-6 md:grid-cols-3">{gymContent.trainers.map((trainer, i) => <motion.article initial="hidden" whileInView="show" viewport={{ once: true, amount: .2 }} variants={reveal} key={trainer.name} className="group relative overflow-hidden border border-[#c8c9c1] bg-[#e5e5dc]"><div className={`relative flex aspect-[1.1] items-end bg-gradient-to-br ${i === 1 ? 'from-[#ff725f]/50 via-[#525969] to-[#252937]' : i === 2 ? 'from-[#d6ff4b]/40 via-[#525969] to-[#252937]' : 'from-[#414a59] via-[#262b36] to-[#171a21]'} p-7`}><span className="font-display text-[8rem] font-black leading-none tracking-[-.08em] text-white/10">{trainer.initials}</span><span className="absolute right-6 top-6 grid size-10 place-items-center rounded-full border border-white/20 text-white/65 group-hover:border-[#d6ff4b] group-hover:text-[#d6ff4b]"><ArrowUpRight size={18} /></span></div><div className="p-6"><h3 className="font-display text-3xl font-bold uppercase text-[#10131b]">{trainer.name}</h3><p className="mt-1 text-sm text-[#59605f]">{trainer.role}</p><p className="mt-5 border-t border-[#c8c9c1] pt-4 text-[11px] leading-5 text-[#7a7e77]">{trainer.note}</p></div></motion.article>)}</div></div></section>;
}
function Inside() {
  return <section id="inside" className="bg-[#171c27] px-5 py-24 md:px-10 md:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid items-end gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading light kicker="A look inside" title={<>Built for<br /><span className="text-[#ff725f]">the next rep.</span></>} body="The energy is in the details: the floor, the focus, the people beside you. Come see why Titan feels different." /><div className="pb-14 text-right"><span className="font-mono-brand text-xs text-[#d9dce5]/45">31° 31′ 20″ N / 74° 20′ 17″ E</span></div></div><div className="grid auto-rows-[210px] grid-cols-2 gap-3 md:auto-rows-[260px] md:grid-cols-4"><div className="relative col-span-2 row-span-2 overflow-hidden bg-[#242a37]"><img src={gymContent.gallery[0].src} alt={gymContent.gallery[0].alt} className="h-full w-full object-cover opacity-85 transition-transform duration-700 hover:scale-105" data-testid="img-gallery-hero" /><div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-[#10131b]/85 p-5"><span className="eyebrow text-[#d6ff4b]">The floor / Clifton</span></div></div>{gymContent.gallery.slice(1).map((image, i) => <div key={image.alt} className={`relative overflow-hidden bg-[#242a37] ${i === 0 ? 'col-span-2' : ''}`}><img src={image.src} alt={image.alt} loading="lazy" className="h-full w-full object-cover opacity-80 grayscale transition-all duration-700 hover:scale-105 hover:grayscale-0" data-testid={`img-gallery-${i + 1}`} /></div>)}</div></div></section>;
}
function Reviews() {
  return <section className="bg-[#ecebe4] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading kicker="Heard on the way out" title={<>The word<br /><span className="text-[#ff725f]">on the street.</span></>} /><div className="mb-14 flex items-center gap-3 border border-[#c8c9c1] bg-[#e5e5dc] px-4 py-3"><div className="flex gap-0.5 text-[#ff725f]">{Array.from({ length: 5 }).map((_, i) => <Star key={i} size={14} fill="currentColor" />)}</div><span className="font-display text-2xl font-bold text-[#10131b]">4.7</span><span className="eyebrow text-[#59605f]">/ 107 reviews</span></div></div><div className="grid gap-5 md:grid-cols-3">{gymContent.testimonials.map((item, i) => <motion.blockquote initial="hidden" whileInView="show" viewport={{ once: true }} variants={reveal} key={item.source + i} className={`flex min-h-[260px] flex-col justify-between p-7 ${i === 1 ? 'bg-[#10131b] text-[#f3f2ea]' : 'border border-[#c8c9c1] bg-[#e5e5dc] text-[#10131b]'}`}><div className={`font-display text-5xl leading-none ${i === 1 ? 'text-[#d6ff4b]' : 'text-[#ff725f]'}`}>"</div><p className="font-display text-2xl font-semibold uppercase leading-[.98] md:text-3xl">{item.quote}</p><footer className={`eyebrow mt-7 ${i === 1 ? 'text-[#d9dce5]/50' : 'text-[#59605f]'}`}>{item.source}</footer></motion.blockquote>)}</div></div></section>;
}
function Visit() {
  return <section id="visit" className="relative overflow-hidden bg-[#10131b] px-5 py-24 md:px-10 md:py-32"><div className="absolute right-0 top-0 h-full w-1/2 bg-[#171c27] [clip-path:polygon(30%_0,100%_0,100%_100%,0%_100%)]" /><div className="relative mx-auto grid max-w-[1440px] gap-16 lg:grid-cols-2"><div><SectionHeading light kicker="Come find us" title={<>Meet us at<br /><span className="text-[#d6ff4b]">Teen Talwar.</span></>} body="Titan lives in Clifton — easy to find, hard to forget. Walk in curious. Walk out with a plan." /><a href="https://www.google.com/maps/search/?api=1&query=Titan+Fitness+Gym+Clifton+Karachi" target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 border-b border-[#d6ff4b] pb-2 text-xs font-bold uppercase tracking-widest text-[#d6ff4b]" data-testid="link-google-maps">Open in Google Maps <ArrowUpRight size={16} /></a></div><div className="grid gap-9 self-end border-l border-white/15 pl-7 md:grid-cols-2 lg:pl-14"><div><div className="eyebrow mb-4 text-[#ff725f]"><MapPin size={13} className="mr-2 inline" />Address</div><p className="max-w-xs text-sm leading-6 text-[#d9dce5]/75">{gymContent.business.address}</p></div><div><div className="eyebrow mb-4 text-[#ff725f]"><Clock3 size={13} className="mr-2 inline" />Hours</div>{gymContent.business.hours.map(([day, time]) => <div key={day} className="flex justify-between gap-4 border-b border-white/10 py-2 text-sm"><span className="text-[#d9dce5]/55">{day}</span><span className="text-right text-[#f3f2ea]">{time}</span></div>)}</div></div></div></section>;
}
function Footer() {
  return <footer className="bg-[#0c0f15] px-5 pb-28 pt-12 md:px-10 md:pb-12"><div className="mx-auto flex max-w-[1440px] flex-col gap-10 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center bg-[#d6ff4b] text-[#10131b]"><Dumbbell size={19} /></span><span className="font-display text-3xl font-black uppercase text-[#f3f2ea]">Titan<span className="text-[#d6ff4b]">.</span></span></div><p className="mt-5 max-w-sm text-sm leading-6 text-[#d9dce5]/45">{gymContent.business.positioning} A training space for Clifton, Karachi.</p></div><div className="flex flex-col gap-4 md:items-end"><div className="flex gap-4"><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram" className="text-[#d9dce5]/55 hover:text-[#d6ff4b]" data-testid="link-instagram"><Instagram size={19} /></a><a href={gymContent.business.whatsapp} target="_blank" rel="noreferrer" aria-label="WhatsApp" className="text-[#d9dce5]/55 hover:text-[#d6ff4b]" data-testid="link-whatsapp-footer"><MessageCircle size={19} /></a></div><span className="eyebrow text-[#d9dce5]/30">© 2025 Titan Fitness Gym · Clifton, Karachi</span></div></div></footer>;
}
function Home() {
  return <div className="noise min-h-[100dvh] overflow-x-hidden"><Header /><main><Hero /><Marquee /><Programs /><Credibility /><Pricing /><Coaches /><Inside /><Reviews /><Visit /></main><Footer /><a href={gymContent.business.whatsapp} target="_blank" rel="noreferrer" className="fixed bottom-5 right-5 z-30 flex items-center gap-3 bg-[#d6ff4b] px-4 py-3.5 text-xs font-bold uppercase tracking-widest text-[#10131b] shadow-[0_12px_35px_rgba(214,255,75,.2)] transition-transform hover:-translate-y-1 md:bottom-7 md:right-7" data-testid="link-whatsapp-floating"><MessageCircle size={18} /><span className="hidden sm:inline">WhatsApp Titan</span></a></div>;
}
function Router() {
  const [location] = useLocation();
  return <ErrorBoundary resetKey={location}><Switch><Route path="/" component={Home} /><Route component={NotFound} /></Switch></ErrorBoundary>;
}
function App() {
  return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>;
}
export default App;